# Generated by Django 2.1.7 on 2019-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Western'), (2, 'Japanese'), (3, 'Chinese'), (4, 'Korean'), (5, 'Indian')], default=1),
        ),
    ]
