# Generated by Django 2.1.7 on 2019-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190428_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Western'), (2, 'Japanese'), (3, 'Chinese'), (4, 'Korean'), (5, 'Indian'), (6, 'Thai')], default=1),
        ),
    ]
