# Generated by Django 2.1.7 on 2019-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Western'), (2, 'Japanese'), (3, 'Chinese'), (4, 'Korean'), (5, 'Indian'), (6, 'Thai')], default=1),
        ),
    ]
