# Generated by Django 2.1.7 on 2019-05-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190503_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
