# Generated by Django 2.1.7 on 2019-05-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewInputDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
