# Generated by Django 2.1.7 on 2019-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20190506_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentInputDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
